### PR TITLE
Delete flathub.json

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by Exalm** [comment]
Why?

**Comment by Exalm** [comment]
But let's see if it builds on arm. If it does, let's merge it, but I have a suspicion it won't.

**Comment by Exalm** [comment]
Oh, it did build. Nice! Can you actually test it on arm? I don't have any devices like that aside from an old android phone.

**Comment by LeandroStanger** [comment]
bot, build

**Pull request merged**
